name: Deploy CI

env:
    TZ: Asia/Shanghai

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'

            - uses: pnpm/action-setup@v3.0.0
              with:
                  version: '8.x'

            - name: Install pnpm dependencies
              run: pnpm install

            - name: Run build task
              run: pnpm build

            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: '-rlgoDzvc -i --delete'
                  SOURCE: './docs/.vitepress/dist/'
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: ${{secrets.REMOTE_TARGET}}
                  SCRIPT_BEFORE: |
                      whoami
                      ls -al
                  SCRIPT_AFTER: |
                      whoami
                      ls -al
                      echo $RSYNC_STDOUT
