name: Blog CI

# 触发条件，push到main分支或者pull request到main分支
on:
    push:
        branches: [main]

    # 支持手动在工作流上触发
    workflow_dispatch:

# 设置时区
env:
    TZ: Asia/Shanghai

# 定义执行任务
jobs:
    # 构建任务
    build:
        runs-on: ubuntu-latest

        # node v20 运行
        strategy:
            matrix:
                node-version: [20]

        steps:
            # 拉取代码
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  # 保留 Git 信息
                  fetch-depth: 0

            # 设置使用 Node.js 版本
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            # 使用 PNPM V8
            - uses: pnpm/action-setup@v2
              name: Install pnpm
              with:
                  version: 8
                  run_install: false

              # 安装依赖
            - name: Install dependencies
              run: pnpm install --frozen-lockfile

              # 构建项目
            - name: Build blog project
              run: |
                  echo ${{ github.workspace }}
                  pnpm build

              # 5. 部署
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v5.0.3
              with:
                  # 登陆的时候的 sshkey 密钥
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  # Remote host 服务器地址（外网IP）
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  # Remote user 用户
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  # Remote port
                  SOURCE: ./blog
                  # 部署路径
                  TARGET: /usr/local/nginx/html
