name: blog

on:
    push:
        branches: ['main']

    workflow_dispatch:

env:
    TZ: Asia/Shanghai

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # 1. 拉取代码
            - uses: actions/checkout@v3
              with:
                  # 保留 Git 信息
                  fetch-depth: 0

            # 2. 安装pnpm
            - uses: pnpm/action-setup@v2
              name: Install pnpm
              with:
                  version: 8
                  run_install: false

            # 3. 安装 依赖
            - name: Install pnpm dependencies
              run: pnpm install --frozen-lockfile

            # 4. 打包
            - name: Run build task
              run: pnpm build

            # 5. 部署
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v4.1.8
              with:
                  # 登陆的时候的 sshkey 密钥
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  # Remote host 服务器地址（外网IP）
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  # Remote user 用户
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  # Remote port
                  SOURCE: ./blog
                  # 部署路径
                  TARGET: /usr/local/nginx/html/web
